services:
  - type: web
    name: crypto-dashboard-complete
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:server
    envVars:
      - key: PORT
        value: 10000
